### ISSUE TITLE
Certain implies values from apps.json aren't valid

### ISSUE THREAD

**Issue by vsnine** [F5-Labs/cryptonice#17]
Hello,

I ran the tool today against a server using IIS and got the following error. 

```
(cryptonice) My Computer: cryptonice me$ cryptonice MyGreatIISSite.tld
Pre-scan checks
-------------------------------------
Scanning MyGreatIISSite.tld on port 443...
Analyzing DNS data for MyGreatIISSite.tld
Fetching additional records for MyGreatIISSite.tld
MyGreatIISSite.tld resolves to <IP>
<IP>:443: OPEN
TLS is available: True
Connecting to port 443 using HTTPS
Reading HTTP headers for MyGreatIISSite.tld
Traceback (most recent call last):
  File "/cryptonice/bin/cryptonice", line 10, in <module>
    sys.exit(main())
  File "/cryptonice/lib/python3.8/site-packages/cryptonice/__main__.py", line 53, in main
    output_data, hostname = scanner_driver(input_data)
  File "/cryptonice/lib/python3.8/site-packages/cryptonice/scanner.py", line 378, in scanner_driver
    redirection_results, http_data = get_http(ip_address, host_sni, port, target_tlsopen, http_body,
  File "/cryptonice/lib/python3.8/site-packages/cryptonice/modules/gethttp.py", line 402, in get_http
    elements = wappalyze(webpage)
  File "/cryptonice/lib/python3.8/site-packages/cryptonice/modules/gethttp.py", line 134, in wappalyze
    cats = apps[app_name]['cats']
KeyError: 'IIS\\;confidence:50'
```

I found that the **implies** field sometimes includes a confidence value, but that doesn't actually match the main key in the apps.json file. I worked around it by adding a few lines to strip off the confidence value and get a app_name variable that matches something in the json file.

**Comment by warburtr0n** [comment]
Hi @vsnine sorry for the delay on this. Wappalyzer changed their JSON format which broke my code. I finally got around to updating things last week so it should all be working again now. Please do download the latest updates and let me know how you get on.

Closing this for not but feel free to re-open if you're still having issues.
