### ISSUE TITLE
AttributeError: 'CipherSuitesScanResult' object has no attribute 'cipher_suite_preferred_by_server'

### ISSUE THREAD

**Issue by MartinThoma** [F5-Labs/cryptonice#22]
```
$ cryptonice https://gogle.com
Pre-scan checks
-------------------------------------
Scanning gogle.com on port 443...
Analyzing DNS data for gogle.com
Fetching additional records for gogle.com
gogle.com resolves to 142.250.74.196
142.250.74.196:443: OPEN
TLS is available: True
Connecting to port 443 using HTTPS
Reading HTTP headers for www.google.com
Queueing TLS scans (this might take a little while...)
0
1
Traceback (most recent call last):
  File "/home/math/.pyenv/versions/3.8.6/bin/cryptonice", line 8, in <module>
    sys.exit(main())
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cryptonice/__main__.py", line 104, in main
    output_data, hostname = scanner_driver(input_data)
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cryptonice/scanner.py", line 427, in scanner_driver
    tls_data = tls_scan(ip_address, str_host, commands_to_run, port)
  File "/home/math/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cryptonice/modules/gettls.py", line 273, in tls_scan
    preferred_cipher_suite = ssl2_result.cipher_suite_preferred_by_server
AttributeError: 'CipherSuitesScanResult' object has no attribute 'cipher_suite_preferred_by_server'
```

## System information

```
$ python --version
Python 3.8.6

$cryptonice -v
1.2.5
```

**Comment by warburtr0n** [comment]
Thanks for submitting this @MartinThoma 

Newer versions of SSLyze have removed this feature as it was proving unreliable. New versions of Cryptonice have this removed, also, so should be fixed now.
