### ISSUE TITLE
error in Docker when scanning localhost 'UnboundLocalError: local variable 'jarm_data' referenced before assignment'

### ISSUE THREAD

**Issue by securestep9** [F5-Labs/cryptonice#23]
how to reproduce - just run with no parameters on a machine with nothing listening on port 443

```
Scanning localhost on port 443...
Analyzing DNS data for localhost
Fetching additional records for localhost
localhost resolves to 127.0.0.1
localhost:443 is closed
Traceback (most recent call last):
  File "/usr/local/bin/cryptonice", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/cryptonice/__main__.py", line 104, in main
    output_data, hostname = scanner_driver(input_data)
  File "/usr/local/lib/python3.7/site-packages/cryptonice/scanner.py", line 459, in scanner_driver
    if jarm_data:
UnboundLocalError: local variable 'jarm_data' referenced before assignment
```

**Comment by warburtr0n** [comment]
Sorry for the delay @securestep9

This should be resolved in the latest release of the library (Master branch will be updated in due course).
